# Generated by Django 4.2.28 on 2026-02-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('movie', 'seat_row', 'seat_col')},
        ),
    ]
