# Generated by Django 4.2.28 on 2026-02-26 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_alter_seat_movie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="seat",
            name="movie",
        ),
    ]
