# Generated by Django 4.2.28 on 2026-02-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_alter_seat_unique_together_remove_seat_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="movie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.movie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("movie", "seat_row", "seat_col")},
        ),
    ]
