# Generated by Django 4.2.28 on 2026-02-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_seat_movie_alter_seat_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="movie_covers/default.jpg", upload_to="movie_covers/"
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.movie"
            ),
        ),
    ]
